# -*- coding: utf-8 -*-
"""선형대수학3주차.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LflXa_v0fnSuuXjgu5XjssAo2xMz7GH7
"""

# 41페이지 행렬 과제: 대각합

# 행렬
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8 ,9]
]

# 대각합 계산
diagonal_sum = 0 # diagonal_sum 변수 초기화
for i in range(len(matrix)):
  diagonal_sum += matrix[i][i]

print("대각합:", diagonal_sum)

# 41페이지 행렬 과제: NumPy로 대각합 구하기

import numpy as np

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("대각합:", np.trace(matrix))
